apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.4-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: app
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root