apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: whatos
      context: ../src
test:
  - image: whatos
    custom:
      - command: ../scripts/unit-tests.sh
        timeoutSeconds: 60
manifests:
  kustomize:
    paths:
      - overlays/dev
deploy:
  statusCheckDeadlineSeconds: 120
  kubectl:
    defaultNamespace: whatos
    hooks:
      after:
        - host:
            command: ["bash", "-c", "../scripts/playwright-tests.sh"]
portForward:
  - resourceType: service
    resourceName: dev-whatos
    namespace: whatos
    port: 8081
    localPort: 8081
