apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: whatos
    context: ../src
test:
  - image: whatos
    custom:
      - command: ../scripts/unit-tests.sh
        timeoutSeconds: 60
deploy:
  statusCheckDeadlineSeconds: 120
  kustomize:
    paths: 
    - overlays/dev-a
    defaultNamespace: whatos
    hooks:
      after:
        - host:
            command: ["bash", "-c", "../scripts/network-tests.sh"]
portForward:
- resourceType: service
  resourceName: dev-whatos
  namespace: whatos
  port: 8081
  localPort: 8081