apiVersion: v1
kind: Service
metadata:
  name: whatos
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: whatos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081